name: tlabaty_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.1.0
  fluttericon: ^2.0.0
  flutter_svg: ^1.1.6

  # State Management & Navigation
  get: ^4.6.1

  # DateTime & Formatting
  jiffy: ^6.4.3
  intl: ^0.20.2

  # HTTP & Networking
  http: ^0.13.4
  url_launcher: ^6.1.2

  # Images & Media
  cached_network_image: ^3.2.0
  image_picker: ^0.8.7+5
  image_pickers: ^2.0.0+2
  lottie: ^1.4.1

  # Animation
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1
  timelines: ^0.1.0

  # Firebase
  firebase_core: ^2.26.0
  firebase_messaging: ^14.9.4
  cloud_firestore: ^4.17.4
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.2.2
  flutter_ringtone_player: ^4.0.0


  # Local Storage
  sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  path: ^1.8.0

  # QR Code & Scanning
  qr_flutter: ^4.0.0

  # UI Components
  dropdown_search: ^3.0.1
  badges: ^2.0.2
  grouped_list: ^4.2.0
  flutter_otp_text_field: ^1.5.1+1

  # Debugging & Development
  device_preview: ^1.3.1
  responsive_builder: ^0.4.2

  # Functional Programming
  dartz: ^0.10.1

  # Location & Maps (نسخ متوافقة مع Flutter 3.8.1)
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatar.png
    - assets/lottie/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
